# Generated by Django 3.2.8 on 2021-11-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='data contato'),
        ),
    ]
