# Generated by Django 4.1.6 on 2023-02-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0005_auto_20211105_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
