# Generated by Django 3.2.8 on 2021-11-06 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Curso')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data Início')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('image', models.ImageField(upload_to='curso_images', verbose_name='Imagem')),
            ],
        )
    ]
