# Generated by Django 3.2.8 on 2021-11-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
